name: unisphere
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  logger: ^2.6.1
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  get_it: ^8.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  injectable: ^2.5.1
  google_fonts: ^6.3.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_native_splash: ^2.4.6
  splash_master: ^0.0.3
  # Map packages
  flutter_map: ^7.0.2
  cached_network_image: ^3.4.1
  geolocator: ^13.0.1
  sqflite: ^2.4.0
  path_provider: ^2.1.4
  latlong2: ^0.9.1
  path: ^1.9.0
  smooth_page_indicator: ^1.2.1
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  go_router_builder: ^4.0.1
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  flutter_gen_runner: ^5.11.0
  injectable_generator: ^2.8.1
  flutter_launcher_icons: ^0.14.4

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: false
  integrations:
    image: true
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/animations/lotties/

flutter_launcher_icons:
  image_path: "assets/icons/unisphere_icon.png"
  android: "launcher_icon"
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/unisphere_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/unisphere_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/unisphere_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/unisphere_logo.png"
  fullscreen: true
